### ISSUE TITLE
Login times out

### ISSUE THREAD

**Issue by cobrabr** [matthewdias/kitsu-slack#2]
Hi,

I just added the Kitsu app to my Slack workspace, but I can't login. Every time I try, I get an `operation_timeout` response:

![image](https://user-images.githubusercontent.com/724969/33035741-3aaf1e3c-cdfa-11e7-99f9-872ef960474f.png)

I tried changing the password to something simpler, but to no avail.

Thanks,
Luciano.

**Comment by matthewdias** [comment]
Hmm that's odd. Are you running your own instance of the app or did you just use the "add to slack" button?

**Comment by cobrabr** [comment]
I used the "Add to Slack" button.

**Comment by frohikey** [comment]
@cobrabr: I had the same problem. Solution is easy - as a login name do NOT use your email but profile URL.

**Comment by matthewdias** [comment]
ah, I guess I need to support email login as well. if i'm being honest tho I probably will wait until Kitsu has proper app support with a hosted authorization screen.

**Comment by cobrabr** [comment]
Using the username has the same effect...

**Comment by matthewdias** [comment]
It looks like Kitsu login takes longer than it used to. We need to switch to an async Slack response, rather than the immediate one that has a 3 second window. Again, I'll probably put this off until proper Kitsu OAuth is a thing, but in the meantime, pull requests are welcome.

**Comment by matthewdias** [comment]
Closed by https://github.com/matthewdias/kitsu-slack/commit/1ac6559a286dea7b935367eb66aa65e490a5f3de
